_app/urls.py
from django.urls import path

from .import views

app_name = '_app'

urlpatterns = [
    path('', views.home, name='index'),
    path('paket-tour/detail/<str:slug>', views.detail, name='detail'),
    path('kontak/', views.kontak, name='kontak'),
    path('paket/', views.paket, name='paket'),
    path('transport/', views.transport, name='transport'),
    path('tentang-kami/', views.tentang_kami, name='tentang_kami'),
    path('galeri/', views.galeri, name='galeri'),

]

shaka_tour/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap


admin.autodiscover()
admin.site.enable_nav_sidebar = False

from _app.sitemaps import PakeSitemaps

sitemaps = {
    'story': PakeSitemaps,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
                            name='django.contrib.sitemaps.views.sitemap'),

    path('', include('_app.urls')),
]

handler404 = '_app.views.error_404'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

_app/models.py
from distutils.command.upload import upload
from email.policy import default
from statistics import mode
from django.db import models
from django.db.models.fields import EmailField
from django.utils.text import slugify
# from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse




KATEGORY_PILIHAN = (
    ('Honeymoon Lombok','Honeymoon Lombok'),
    ('Tour Lombok','Tour Lombok'),
    ('Harian Lombok','Harian Lombok')
)

class Kategory(models.Model):
    nama = models.CharField(max_length=200, choices=KATEGORY_PILIHAN, default='')
    def __str__(self):
        return self.nama


class Paket_tour(models.Model):
    nama_paket = models.CharField(max_length=200, default="")
    Kategory = models.ForeignKey(Kategory, related_name='paket_tour', default="", on_delete=models.CASCADE)
    deskripsi = models.TextField()
    poto       = models.ImageField(upload_to='paket_tour', default='')  
    durasi     = models.CharField(max_length=200)
    harga      = models.CharField(max_length=200)
    itenerary = RichTextUploadingField()
    slug = models.SlugField(blank=True, null=True, editable=False)

    def __str__(self):
        return self.nama_paket 
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.nama_paket)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('_app:detail', args={self.slug})

class Detail_harga(models.Model):
    paket = models.ForeignKey(Paket_tour, related_name='detail_harga', on_delete=models.CASCADE)
    jumlah = models.CharField(max_length=200)
    tour = models.CharField(max_length=100)
    tour_hotel = models.CharField(max_length=100)   

    def __str__(self):
        return self.jumlah


class Populer(models.Model):
    nama = models.CharField(max_length=200)
    poto       = models.ImageField(upload_to='populer', default='')  
    def __str__(self):
        return self.nama


class Paket_transport(models.Model):
    nama_tujuan = models.CharField(max_length=200) 
    harga       = models.IntegerField()

    def __str__(self):
        return self.nama_tujuan



class Testimony(models.Model):
    nama = models.CharField(max_length=100)
    poto = models.ImageField(upload_to="userTestimony", default='')
    komentar = models.TextField()


    def __str__(self):
        return self.nama


class Blog(models.Model):
    judul = models.CharField(max_length=100)
    content = models.TextField()
    penulis = models.CharField(max_length=100, default="")    

class Pesanan_paket(models.Model):
    nama          = models.CharField(max_length=200)
    alamat        = models.CharField(max_length=200)
    nomor_hp      = models.CharField(max_length=200)
    jumlah_orang  = models.CharField(max_length=100)
    tanggal_jemput= models.DateField()
    paket         = models.CharField(max_length=200)


    def __str__(self):
        return self.nama


class Galeri(models.Model):
    judul = models.CharField(max_length=200)
    poto = models.ImageField(upload_to='galeri', default='')

    def __str__(self):
        return self.judul


class Kontak(models.Model):
    nama  = models.CharField(max_length=100) 
    email = models.EmailField()
    pesan = models.TextField()

    def __str__(self):
        return self.nama


class Banner(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="banner", default='')

    def __str__(self):
        return self.title
    

        

        

_app/views.py
from django.db.models.fields import EmailField
from django.shortcuts import render,redirect
from django.contrib import messages
from .models import ( 
        Paket_transport, Paket_tour, Pesanan_paket, Kontak, Pesanan_paket, 
        Banner, Populer,Testimony, Kategory
    )

def home(request):
    paket_tour = Paket_tour.objects.all()
    banners = Banner.objects.all()
    populers = Populer.objects.all()
    testimony = Testimony.objects.all()
    kategory = Kategory.objects.all()

    context = {
        'title':'Agen Wisata Lombok | Home',
        'paket_tours': paket_tour,
        'banners':banners,
        'populers':populers,
        'testy':testimony,
        'kategory':kategory
    }

    if(request.method == 'POST'):
        id_kategory = request.POST.get('ktr')
        context['paket_tours'] = Paket_tour.objects.filter(Kategory=id_kategory)
        return render(request,'home.html', context)   
    else:
        context['paket_tours'] = Paket_tour.objects.all()

    return render(request,"home.html", context)




def detail(request, slug):
    paket = Paket_tour.objects.get(slug=slug)
    paket_other = Paket_tour.objects.exclude(slug=slug)


    context = {
        'title':'Detail',
        'paket': paket,
        'paket_other': paket_other
    }

    if request.method == 'POST':
        Pesanan_paket.objects.create(
            nama            = request.POST.get('nama'),
            alamat          = request.POST.get('alamat'),
            nomor_hp        = request.POST.get('nomor_hp'),
            jumlah_orang    = request.POST.get('jumlah_orang'),
            tanggal_jemput  = request.POST.get('tanggal_penjemputan'),
            paket           = paket.nama_paket
        )

        Pesanan_paket.save
        messages.success(request,'Pemesanan paket sukses, kami akan menghubungi anda via wa')

        return redirect('_app:index')
    return render(request,'detail.html',context)

def kontak(request):
    context = {
        'title':'Kontak'
    }

    if request.method == 'POST':
        nama  = request.POST.get('nama')
        email = request.POST.get('email')
        pesan = request.POST.get('pesan')

        Kontak.objects.create(
            nama = nama,
            email =email,
            pesan = pesan
        )
        Kontak.save
        messages.success(request,'Terimakasih, pesan anda sudah terkirim')

    else:
        return render(request,'kontak.html',context)    

    return render(request,'kontak.html',context)


def paket(request):
    return render(request,'paket.html')

def transport(request):
    paket_transports = Paket_transport.objects.all()
    context = {
        'title':'transport',
        'paket_transport': paket_transports
    }

    return render(request,'transport.html', context)


def tentang_kami(request):

    return render(request,'tentang_kami.html',context={'title':'Tentang kami'})
    

def galeri(request):

    return render(request,'galeri.html',context={'title':'Gallery'})


def error_404(request, exception):
    return render(request,'404.html')

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="Shaka_tour" property="og:description" content="Salah satu agen wisata terpercaya yang ada di pulau lombok, yang dapat memudahkan perjalanan wisata anda dengan keluarga, disini kami hadir untuk anda">
    <meta name="shaka_tour" content="shaka tour lombok">
    <link rel="icon" type="image/x-icon" href="{% static 'img/logoku.png' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Suez+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>
      .navbar-toggler-icon{
      background-color: #58566e;
      display: block;
      width: 30px;
      height: 3px;
    }
    .navbar-toggler-icon:active{  
      border: none;
    }

    .icon-middle{
        margin: 6px;
    }
    </style>
    <title>{{title}}</title>
  </head>
  <body>
    {% include 'navbar.html' %}



    <!-- kontens? -->
    {% block content %}


    {% endblock content %}


    <a href="https://api.whatsapp.com/send?phone=+6287860371458&text=Hii%20kak%2C%20minta%20info%20untuk%20paket%20wisatanya%20dong%20!!!">

      <div class="wa" style="position: fixed;">
        <img src="{% static 'img/whatsapp.svg' %}" width="60" alt="">
      </div>
    </a>

    <div class="footer">
      <div class="container">
        <div class="row">
          <div class="col-12 col-md-4">
            <img class="mb-4" src="{% static 'img/logo_footer.png' %}" width="150" alt="">
            <!-- <p>&copy; 2021 Shaka Travel Lombok</p> -->
            <p style="margin-top: 10px;">Shaka tour</p>
            <p>Alamat : jln.Tgh Ibrahim Khalidi</p>
            <p>Kediri, NTB, Indonesia</p>
            <p>WA : +6287860371458</p>
            <p>Email : shakatour2021@gmail.com</p>
          </div>
          <div class="col-12 col-md-4 mt-5">
            <h3 class="mb-5" style="color: white;">Perusahaan</h3>
            <a style="text-decoration: none;" href=""><p>Tentang</p></a>
            <a style="text-decoration: none;" href=""><p>Galeri</p></a>
            <a style="text-decoration: none;" href=""><p>Kontak</p></a>
          </div>
          <div class="col-12 col-md-4 mt-5">
            <h3 class="mb-5" style="color: white;">Destinasi populer</h3>
            <a style="text-decoration: none;" href="https://id.wikipedia.org/wiki/Pantai_Kuta,_Lombok"><p>Pantai kuta mandalika</p></a>
            <a style="text-decoration: none;" href="https://id.wikipedia.org/wiki/Sirkuit_Internasional_Mandalika"><p>Sirkuit mandalika</p></a>
            <a style="text-decoration: none;" href="https://id.wikipedia.org/wiki/Kepulauan_Gili#:~:text=Kepulauan%20Gili%20atau%20Tiga%20Gili,destinasi%20wisata%20populer%20bagi%20wisatawan."><p>3 gili</p></a>
          </div>
          <hr style="color: wheat;">
          <p class="text-center">Copyright &copy; 2020 All Right Reserved, Shaka tour</p>
        </div>
      </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    {% if messages %}

      {% for message in messages %}
          <script>
            Swal.fire(
              '{{message}}',
            )
          </script>
      {% endfor %}

     {% endif %}


     <script type="text/javascript">
      function Angkasaja(evt) {
      var charCode = (evt.which) ? evt.which : event.keyCode
      if (charCode > 31 && (charCode < 48 || charCode > 57))
      return false;
      return true;
      }
      
      </script>

      <script type="text/javascript">
        window.onload=function(){//from ww  w . j  a  va2s. c  o  m
        var today = new Date().toISOString().split('T')[0];
        document.getElementsByName("setTodaysDate")[0].setAttribute('min', today);
        }

      </script> 

      <script src="https://kit.fontawesome.com/eb5100ca45.js" crossorigin="anonymous"></script>


  </body>
</html>

templates/dashboard/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Admin</title>

    <!-- Custom fonts for this template-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'dashboard/css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Admin <sup>2</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="index.html">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Interface
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Home</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-sign-out-alt"></i>
                    <span>Logout</span>
                </a>
            </li>         

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                       <h5>logout</h5>

                        <!-- Nav Item - Alerts -->

                        <!-- Nav Item - Messages -->
                        

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                
                {% block content %}
                    
                {% endblock content %}
                    
                
                <!-- /.container-fluid -->

            </div>  
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
   

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'dashboard/js/jquery.min.js' %}"></script>
    <script src="{% static 'dashboard/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'dashboard/js/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'dashboard/js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'dashboard/js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'dashboard/js/chart-area-demo.js' %}"></script>
    <script src="{% static 'dashboard/js/chart-pie-demo.js' %}"></script>

</body>

</html>

templates/dashboard/detail_pesanan_baru.html
{% extends 'dashboard/base.html' %}
{% load static %}

templates/dashboard/index.html
{% extends 'dashboard/base.html' %}
{% load static %}



{% block content %}
<div class="container-fluid">
    <div class="row">

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <a href="{% url '_app:detail_pesanan_baru' %}">
                <div class="card border-left-primary shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                    Pesanan baru</div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">{{pesanan_baru.count}}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                Berjalan</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{pesanan_berjalan.count}}</div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                Selesai</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{pesanan_selesai.count}}</div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Content Row -->

    <div class="row">

        <!-- Area Chart -->
        <div class="col-xl-8 col-lg-7">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Earnings Overview</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="chart-area">
                    
                    </div>
                </div>
            </div>
        </div>

        <!-- Pie Chart -->
        <div class="col-xl-4 col-lg-5">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Revenue Sources</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="chart-pie pt-4 pb-2">
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Content Row -->
    <div class="row">

        <!-- Content Column -->

    </div>

</div>    
{% endblock content %}
    


    

templates/dashboard/login.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Login</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                    </div>
                                    <form class="user">
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user"
                                                id="exampleInputEmail" aria-describedby="emailHelp"
                                                placeholder="Enter Email Address...">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                id="exampleInputPassword" placeholder="Password">
                                        </div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox small">
                                                <input type="checkbox" class="custom-control-input" id="customCheck">
                                                <label class="custom-control-label" for="customCheck">Remember
                                                    Me</label>
                                            </div>
                                        </div>
                                        <a href="index.html" class="btn btn-primary btn-user btn-block">
                                            Login
                                        </a>
                                        <hr>
                                        <a href="index.html" class="btn btn-google btn-user btn-block">
                                            <i class="fab fa-google fa-fw"></i> Login with Google
                                        </a>
                                        <a href="index.html" class="btn btn-facebook btn-user btn-block">
                                            <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook
                                        </a>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="forgot-password.html">Forgot Password?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="register.html">Create an Account!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

templates/form-transport.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Transportasi</h1>
</body>
</html>

templates/navbar.html
{% load  static %}
{% load active_link_tags %}



<div class="header-atas">
  <!-- <div class="container"> -->
    <nav class="navbar navbar-expand-lg bg-default p-0 mt-2">
      <div class="container mt-3">
        <a class="navbar-brand" href="{% url '_app:index' %}" style="color: #fff;">
          <img src="{% static 'img/home/logokunew.png' %}" alt="" width="110">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon icon-top"></span>
          <span class="navbar-toggler-icon icon-middle"></span>
          <span class="navbar-toggler-icon icon-buttom"></span>
        </button>
        <div class="collapse navbar-collapse mt-3" id="navbarNav">
          <ul class="navbar-nav p-0">
            <li class="nav-item align-self-center">
              <a class="nav-link" aria-current="page" href="{% url '_app:index' %}">Home</a>
            </li>
            <li class="nav-item align-self-center">
              <a class="nav-link {% active_link '_app:tentang_kami' 'active'%}" aria-current="page" href="{% url '_app:tentang_kami' %}">Tentang kami</a>
              <div class=" {% active_link '_app:tentang_kami' 'underline'%}"></div>
            </li>
            <li class="nav-item align-self-center">
              <a class="nav-link " aria-current="page" href="{% url '_app:transport' %}">Transportasi</a>
                  <div class="{% active_link '_app:transport' 'underline'%}"></div>
            </li>
            <li class="nav-item align-self-center">
              <a class="nav-link " aria-current="page" href="{% url '_app:galeri' %}">Galeri</a>
              <div class="{% active_link '_app:galeri' 'underline'%}" ></div>
            </li>
            <li class="nav-item align-self-center">
              <a class="nav-link" aria-current="page" href="{% url '_app:kontak' %}">Kontak</a>
              <div class=" {% active_link '_app:kontak' 'underline'%}"></div>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  <!-- </div> -->
</div>


  